name: Build and deploy ASP.Net Core app to Azure Web App - emr-clinic-romza

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore Code/Solutions/FromzaEMR.sln

      - name: Build with MSBuild
        run: msbuild Code/Solutions/FromzaEMR.sln /p:Configuration=Release /p:Platform="Any CPU" /m

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish web project
        run: dotnet publish Code/Websites/FromzaEMR/FromzaEMR.csproj -c Release -o "${{ runner.temp }}/publish" --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{ runner.temp }}/publish"

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_304457BF675647C6B1EA98543E8433C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_262EADA575924FE1B89E53722DB4F498 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AC482833ED0E46DDBC3A1FC4DCF62B2A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'emr-clinic-romza'
          slot-name: 'Production'
          package: .
